### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by obelix05** [bieniu/ha-thermostats-update#1]
Hello,

I'm unfortunately not able to run this application in my home assistant istance. I have a HA 0.98.2 running in a docker container. I downloaded the zip file from github and install the content of the apps/* folder in my config/apps* folder. After a restart of HA i try to add the example to my configuration.yml but running the "Check Config" brings the error "Configuration invalid
Component error: thermostats_update - Integration thermostats_update not found."
Do you have any clue for me on how to get this app up and running?

**Comment by bieniu** [comment]
You have to install AppDaemon to use this app.
