### ISSUE TITLE
App crashes Zwave Thermostat

### ISSUE THREAD

**Issue by v1027m** [bieniu/ha-thermostats-update#2]
It could very well be something I'm doing wrong but once I run this app it crashes my 

'climate.thermostat'
What I mean is the control for my thermostat is killed, and I can only see the remote temperature sensor on my Lovelace UI and the 'climate.thermostat' entity is lost in my Zwave network until I stop and restart my Zwave network.

I copy the config exactly as you have it here, I just only have one thermostat so there is only one rooms and one remote sensor in my config.

Not sure if this matters but I'm using a smartthings motion sensor as my 'sensor.living_room_temperature' and I have the HoneyWell Intrusion TH6320ZW2003 as my thermostat.

**Comment by bieniu** [comment]
I doubt that it's possible to crash OpenZWave node by this app. Maybe you overrided known state of the entity? If entity's state is known you have to use `temp_only: true` argument, if entity's `current_temperature` attribute is known you have to use `state_only: true` argument.

**Comment by v1027m** [comment]
That's exactly what it was, thanks for the quick reply.
I overlooked the 'temp_only' config option and is false by default. Once I added it in and set it to 'true' everything worked out smoothly.
Knew it had to be operator error, again thank you.

**Comment by kabturek** [comment]
I also observed this behavior with Appdaamon 4 - the attributes are reset/lost when using set_state (with appdaemon 3 it works properly). Might be connected with https://github.com/home-assistant/appdaemon/issues/904 - the workaround is to get the state before and update the attributes. Created a pull request with the changes i had to make to make it work https://github.com/bieniu/ha-ad-thermostats-update/pull/3
