### ISSUE TITLE
Repostitory structure for 0.4.2 is not compliant

### ISSUE THREAD

**Issue by joselito11** [bieniu/ha-thermostats-update#8]
I want to install it via HACS and get this error when adding new repository: Repostitory structure for 0.4.2 is not compliant
Ca be this updated?

**Comment by bieniu** [comment]
This is the default repository in HACS, you shouldn't add anything.

**Comment by joselito11** [comment]
I dont have it default in HACS

**Comment by joselito11** [comment]
Added manual to HA config, but get this error when calling automation:
Logger: homeassistant.components.python_script.thermostat_update.py
Source: components/python_script/__init__.py:222
Integration: Python Scripts (documentation, issues)
First occurred: 15:42:48 (7 occurrences)
Last logged: 17:01:03

Error executing script: __import__ not found
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 222, in execute
    exec(compiled.code, restricted_globals)
  File "thermostat_update.py", line 51, in <module>
ImportError: __import__ not found

**Comment by bieniu** [comment]
> I dont have it default in HACS

So your HACS is not configured correctly to use AppDaemon apps.

**Comment by joselito11** [comment]
Have it now after installing AppDaemon, sorry and thank you!
